version: '3.3'

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=citizix_user
      - MYSQL_DATABASE=citizix_db
  employee-frontend:
    image: employee-frontend:latest
    ports: 
      - 4200:4200
    build: ./
    command: > 
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"